###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.

#You can merge multiple samples and give the sample barcodes in a text file with -b option.
#You can separate them later from the count tables.

# Run as
# bash /stornext/Projects/GenomicsRnD/brown.d/zUMIs/zUMIs.sh -c -y \
#    /stornext/Home/data/allstaff/b/brown.d/Projects/G000233_DRAC-Seq/config/zUMIs/S000424_zUMI.yaml

# To generate the combined fastq run:
# Concatenate multiple fastqs with:
# cat *I1_001.fastq.gz > S000424_TURBO_S1_I1_001.fastq.gz
# cat *R1_001.fastq.gz > S000424_TURBO_S1_R1_001.fastq.gz
# cat *R2_001.fastq.gz > S000424_TURBO_S1_R2_001.fastq.gz

# Make sure to have a reference genome indexed with the same version of STAR
###########################################

#define a project name that will be used to name output files
project: G000278_Brain_TMZ
#Sequencing File Inputs:
sequence_files:
  file1:
    name: /vast/scratch/users/brown.d/S000446/fastq/TURBO_Brain_TMZ_S1_R2_001.fastq.gz
    base_definition:
      - BC(1-10)
      - UMI(28-37)
  file2:
    name: /vast/scratch/users/brown.d/S000446/fastq/TURBO_Brain_TMZ_S1_R1_001.fastq.gz
    base_definition:
      - cDNA(1-52)

#reference genome setup
reference:
  STAR_index: /stornext/Projects/score/Indexes/hg19_and_mm10/Human_Mouse_Combined_STARnoGTF
  GTF_file: /stornext/Projects/score/Indexes/hg19_and_mm10/genes.gtf
  exon_extension: no #extend exons by a certain width?
  extension_length: 0 #number of bp to extend exons by
  scaffold_length_min: 0 #minimal scaffold/chromosome length to consider (0 = all)
  additional_files:
  additional_STAR_params:

#output directory
out_dir: /vast/scratch/users/brown.d/S000446/zUMI_temp

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 12
mem_limit: null  #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: /stornext/Home/data/allstaff/b/brown.d/Projects/G000278_TurboCapSeq/metadata/references/version2_read1_wellBC.csv
  automatic: no #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 1 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: no #can be set to no for exon-only counting.
  downsampling: '5000,10000,20000,50000,100000,200000,500000,1000000' #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 100020000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  write_ham: no #If hamming distance collapse of UMI sequences is performed, write out mapping tables & UB corrected bam files.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: no #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths
zUMIs_directory: /vast/scratch/users/brown.d/zUMIs
read_layout: SE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
